export const MY_POPUP = "MY_POPUP"
export const HOME_DATA = "HOME_DATA"
export const FORM_DATA = "FORM_DATA"
export const MY_MODAL = "API_DATA"
export const MY_NUMBER = "MY_NUMBER"
export const TABLE_VALUE = "TABLE_VALUE"
export const ADD_POPUP = "ADD_POPUP"
export const EXPENSES_VALUE = "EXPENSES_VALUE"
export const INCOME_VALUE = "INCOME_VALUE"
export const INCOME_MODAL = "INCOME_MODAL"
export const INCOME_TOTAL = "INCOME_TOTAL"
export const DELETE_OBJ = "DELETE_OBJ"
export const DELETE_INCOME = "DELETE_INCOME"

